########## nebula-graphd v3.6.0 配置 ##########
# Graph服务配置，用于接收客户端查询

--meta_server_addrs=de-nebula-metad:9559
--local_ip=de-nebula-graphd
--port=9669
--ws_ip=de-nebula-graphd
--ws_http_port=19669
--log_path=/logs/graph
--daemonize=false
--pid_file=/var/run/nebula-graphd.pid
--timezone_name=UTC+08:00

# 系统配置
--num_workers=4
--num_io_threads=4
--num_netio_threads=4
--session_max_idle_time_secs=14400
--session_max_processing_time_secs=60
--max_connections=20000
--min_connection_pool_size=10
--max_connection_pool_size=1000

# 查询配置
--max_jobs_size=32
--max_step_size=64
--enable_optimizer=true
--accept_partial_success=false