########## nebula-storaged v3.6.0 配置 ##########
# Storage服务配置，用于数据存储

--meta_server_addrs=de-nebula-metad:9559
--local_ip=de-nebula-storaged
--port=9779
--ws_ip=de-nebula-storaged
--ws_http_port=19779
--data_path=/data/storage
--log_path=/logs/storage
--daemonize=false
--pid_file=/var/run/nebula-storaged.pid
--timezone_name=UTC+08:00

# 系统配置
--num_workers=4
--num_io_threads=4
--num_netio_threads=4
--raft_heartbeat_interval_secs=1
--raft_election_timeout=5
--raft_log_path=/logs/storage/raft

# 存储配置
--custom_filter_interval=64
--enable_partitioned_index_filter=false