apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-autoscaler.configmapName" . }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
