-- Flyway 基线迁移：data-standard
-- 由 Hibernate 按 PostgreSQL 方言生成（jakarta.persistence.schema-generation.scripts.action=create），
-- 字段与 JPA 实体一一对应，非手写。重新生成：bash scripts/gen-db-baseline.sh platform/data-standard
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table data_standards (created_at timestamp(6), id bigint generated by default as identity, updated_at timestamp(6), description varchar(2000), rule varchar(4000), json_schema varchar(8000), category varchar(255), name varchar(255) not null, status varchar(255), tenant_id varchar(255), version varchar(255), primary key (id));
create table standard_categories (created_at timestamp(6), id bigint generated by default as identity, parent_id bigint, updated_at timestamp(6), description varchar(2000), code varchar(255) not null, name varchar(255) not null, tenant_id varchar(255), primary key (id));
