-- Flyway 基线迁移：infra-provider-private
-- 由 Hibernate 按 PostgreSQL 方言生成（jakarta.persistence.schema-generation.scripts.action=create），
-- 字段与 JPA 实体一一对应，非手写。重新生成：bash scripts/gen-db-baseline.sh platform/infra-provider-private
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table private_clusters (control_plane_count integer, worker_count integer, created_at timestamp(6), id bigint generated by default as identity, updated_at timestamp(6), cluster_name varchar(255), error_message varchar(255), k8s_version varchar(255), pod_cidr varchar(255), provider varchar(255), service_cidr varchar(255), status varchar(255), tenant_id varchar(255), vm_json TEXT, primary key (id));
