-- Flyway 基线迁移：sql-gateway
-- 来源：逐个 JPA 实体逐字段推导（@Table/@Id/@GeneratedValue/@Column/@Enumerated/@Lob/
--       @ElementCollection 等），类型按 PostgreSQL 方言映射：
--         Long+IDENTITY → bigint generated by default as identity；String 默认 varchar(255)；
--         Instant → timestamp(6) with time zone；@Lob String → oid；Boolean → boolean；
--         @Enumerated(STRING) → varchar(255)。
-- 实体→表映射依据（文件:行号）：
--   route_rules                      ← RouteRule.java:22,38-58
--   rewrite_rules                    ← RewriteRule.java:32,40-75
--   materialized_view_definitions    ← MaterializedViewDefinition.java:39,45-104
--   virtual_table_definitions        ← VirtualTableDefinition.java:52-168
--   virtual_table_columns            ← VirtualTableDefinition.java:121-126 + ColumnDefinition.java:22-42
-- 说明：本环境无法运行 scripts/gen-db-baseline.sh（Maven 离线缺 tools.jackson:jackson-bom:3.1.7，
--       且本地仓库不可写），故本文件为按实体逐字段手写；请在可联网环境重跑生成器复核。
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table route_rules (id bigint generated by default as identity, tenant_id varchar(255), pattern varchar(255), engine varchar(255), priority integer, enabled boolean, primary key (id));
create table rewrite_rules (id bigint generated by default as identity, rule_name varchar(255), rule_type varchar(255), target_view varchar(255), source_table_pattern varchar(255), priority integer, enabled boolean, description varchar(255), primary key (id));
create table materialized_view_definitions (id bigint generated by default as identity, view_name varchar(255), source_table varchar(255), definition_sql oid, query_sql oid, dimension_columns varchar(255), measure_columns varchar(255), refresh_strategy varchar(255), last_refresh_time timestamp(6) with time zone, enabled boolean, priority integer, description varchar(255), primary key (id));
create table virtual_table_definitions (id bigint generated by default as identity, table_name varchar(255) not null, tenant_id varchar(255) not null, data_source_type varchar(255) not null, connection_config oid not null, source_object varchar(255) not null, materialization_strategy varchar(255) not null, materialized_table_name varchar(255), refresh_interval_seconds integer, last_refresh_time timestamp(6) with time zone, enabled boolean not null, description varchar(255), created_at timestamp(6) with time zone, updated_at timestamp(6) with time zone, primary key (id), constraint uk_virtual_table_tenant_name unique (tenant_id, table_name));
create table virtual_table_columns (table_id bigint not null, name varchar(255), type varchar(255), nullable boolean, comment varchar(255));
alter table if exists virtual_table_columns add constraint fk_virtual_table_columns_table foreign key (table_id) references virtual_table_definitions;
create index idx_virtual_table_tenant on virtual_table_definitions (tenant_id);
create index idx_virtual_table_source on virtual_table_definitions (data_source_type);
