apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager.serviceName" . }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cert-manager.selectorLabels" . | nindent 4 }}
