apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seatunnel.configmapName" . }}
  labels:
    {{- include "seatunnel.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | toString | quote }}
  {{- end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | toString | quote }}
  {{- end }}
