﻿piVersion: v2
name: infra-provider-private
description: "私有云供应 - 私有云 VM 资源供应 - 数据引擎大数据平台"
type: application
version: 2.0.0
appVersion: "2.0.0"
home: https://github.com/DataEngineBDP
maintainers:
  - name: DataEngineBDP Team
    email: platform@shuqing.example.com
keywords:
  - provider
  - private
  - infra
  - shuqing-platform
  - platform
# 部署目标 namespace（仅文档语义，实际由 helm -n 指定）
namespace: sq-system
