apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.configmapName" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | toString | quote }}
  {{- end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
