{{- if .Values.serviceAccount.create -}}
# ServiceAccount - 导入 Job 专用服务账号（T019）
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finance-template.serviceAccountName" . }}
  namespace: {{ include "finance-template.namespace" . }}
  labels:
    {{- include "finance-template.labels" . | nindent 4 }}
    {{- include "finance-template.templateLabels" . | nindent 4 }}
  annotations:
    {{- include "finance-template.templateAnnotations" . | nindent 4 }}
{{- end -}}
