# 基础 Service · encaps-layer 配套服务
apiVersion: v1
kind: Service
metadata:
  name: encaps-layer
  labels:
    app.kubernetes.io/name: encaps-layer
    app.kubernetes.io/instance: platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: encaps-layer
    app.kubernetes.io/instance: platform
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP