-- Flyway 基线迁移：master-data
-- 由 Hibernate 按 PostgreSQL 方言生成（jakarta.persistence.schema-generation.scripts.action=create），
-- 字段与 JPA 实体一一对应，非手写。重新生成：bash scripts/gen-db-baseline.sh platform/master-data
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table master_data (created_at timestamp(6), id bigint generated by default as identity, updated_at timestamp(6), attributes varchar(8000), data_key varchar(255) not null, data_value varchar(255) not null, model_code varchar(255) not null, status varchar(255), tenant_id varchar(255), version varchar(255), primary key (id));
create table master_data_models (created_at timestamp(6), id bigint generated by default as identity, updated_at timestamp(6), description varchar(2000), fields_schema varchar(8000), code varchar(255) not null, name varchar(255) not null, tenant_id varchar(255), primary key (id));
