apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sql-gateway.configmapName" . }}
  labels:
    {{- include "sql-gateway.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: |
    {{- if kindIs "map" $val }}
      {{- $val | toYaml | nindent 4 }}
    {{- else }}
      {{- $val | nindent 4 }}
    {{- end }}
  {{- end }}
