apiVersion: v2
name: doris
description: Apache Doris 实时数仓 - 数据引擎大数据平台
type: application
version: 2.0.0
appVersion: "2.0.0"
home: https://github.com/DataEngineBDP
maintainers:
  - name: DataEngineBDP Team
    email: platform@shuqing.example.com
keywords:
  - big-data
  - doris
  - shuqing-platform
