-- Flyway 基线迁移：lineage-analyzer
-- 来源：逐个 JPA 实体逐字段推导（@Table/@Id/@GeneratedValue/@Column/@Enumerated/@Index/@UniqueConstraint 等），
--       类型按 PostgreSQL 方言映射：
--         Long+IDENTITY → bigint generated by default as identity；String @Column(length=N) → varchar(N)；
--         @Enumerated(STRING) → varchar(N)（取 @Column(length)）；Instant → timestamp(6) with time zone。
-- 实体→表映射依据（文件:行号）：
--   lineage_edge ← LineageEdge.java:26,44-75（RelationType 枚举 :37-42；索引/唯一约束 :27-33）
--   lineage_node ← LineageNode.java:27,43-78（NodeType 枚举 :36-41；索引/唯一约束 :28-32）
-- 说明：本环境无法运行 scripts/gen-db-baseline.sh（Maven 离线缺 tools.jackson:jackson-bom:3.1.7，
--       且本地仓库不可写），故本文件为按实体逐字段手写；请在可联网环境重跑生成器复核。
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table lineage_edge (id bigint generated by default as identity, source_full_name varchar(512) not null, target_full_name varchar(512) not null, relation_type varchar(32) not null, source_sql varchar(4096), dialect varchar(16), expression varchar(1024), created_at timestamp(6) with time zone not null, primary key (id), constraint uk_edge_pair unique (source_full_name, target_full_name, relation_type));
create table lineage_node (id bigint generated by default as identity, full_name varchar(512) not null unique, node_type varchar(16) not null, schema_name varchar(128), table_name varchar(128), column_name varchar(128), display_name varchar(256), created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, primary key (id), constraint uk_node_full_name unique (full_name));
create index idx_edge_source on lineage_edge (source_full_name);
create index idx_edge_target on lineage_edge (target_full_name);
create index idx_edge_relation_type on lineage_edge (relation_type);
create index idx_node_full_name on lineage_node (full_name);
create index idx_node_type on lineage_node (node_type);
