-- Flyway 基线迁移：encaps-tenant
-- 来源：逐个 JPA 实体逐字段推导（@Table/@Id/@GeneratedValue/@Enumerated 等），类型按 PostgreSQL 方言映射：
--         Long+IDENTITY → bigint generated by default as identity；Long → bigint；
--         String 默认 varchar(255)；LocalDateTime → timestamp(6)（无时区）；
--         @Enumerated(STRING) → varchar(255)。
--       注：实体上的 @NotNull/@NotBlank 属 Bean Validation，Hibernate 6+ 已不再据此生成 NOT NULL，
--           故对应列保持可空（应用层校验）。
-- 实体→表映射依据（文件:行号）：
--   quotas     ← Quota.java:34,38-100（QuotaStatus 枚举 :114-127）
--   workspaces ← Workspace.java:36,40-72（WorkspaceStatus 枚举 :84-93）
-- 注意：本模块与 encaps-layer 有同名租户/工作空间表，prod 必须用独立 schema（encaps_tenant）隔离。
-- 说明：本环境无法运行 scripts/gen-db-baseline.sh（Maven 离线缺 tools.jackson:jackson-bom:3.1.7，
--       且本地仓库不可写），故本文件为按实体逐字段手写；请在可联网环境重跑生成器复核。
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table quotas (id bigint generated by default as identity, workspace_id bigint, tenant_id bigint, cpu_limit varchar(255), memory_limit varchar(255), storage_limit varchar(255), pod_limit varchar(255), pvc_limit varchar(255), service_limit varchar(255), max_cpu_per_pod varchar(255), max_memory_per_pod varchar(255), min_cpu_per_pod varchar(255), min_memory_per_pod varchar(255), status varchar(255), created_at timestamp(6), updated_at timestamp(6), primary key (id));
create table workspaces (id bigint generated by default as identity, name varchar(255), tenant_id bigint, description varchar(255), status varchar(255), namespace varchar(255), resource_quota varchar(255), network_policy varchar(255), created_at timestamp(6), updated_at timestamp(6), primary key (id));
