apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-api.configmapName" . }}
  labels:
    {{- include "query-api.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{- if $val }}
  {{ $key }}: {{ $val | toString | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: |
    {{- if kindIs "map" $val }}
      {{- $val | toYaml | nindent 4 }}
    {{- else }}
      {{- $val | nindent 4 }}
    {{- end }}
  {{- end }}
