apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.configmapName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | toString | quote }}
  {{- end }}
