-- Flyway 基线迁移：stream-batch-scheduler
-- 由 Hibernate 按 PostgreSQL 方言生成（jakarta.persistence.schema-generation.scripts.action=create），
-- 字段与 JPA 实体一一对应，非手写。重新生成：bash scripts/gen-db-baseline.sh platform/stream-batch-scheduler
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table dag_run (biz_time timestamp(6) with time zone, created_at timestamp(6) with time zone not null, duration_ms bigint, end_time timestamp(6) with time zone, id bigint generated by default as identity, source_run_id bigint, start_time timestamp(6) with time zone, run_type varchar(16) not null check ((run_type in ('MANUAL','SCHEDULED','RERUN','BACKFILL'))), status varchar(16) not null check ((status in ('PENDING','RUNNING','SUCCESS','FAILED','SKIPPED','CANCELLED'))), tenant_id varchar(64) not null, dag_id varchar(128) not null, triggered_by varchar(128), dag_snapshot TEXT not null, error_message TEXT, node_results_json TEXT, primary key (id));
create table sb_job (created_at timestamp(6) with time zone not null, id bigint generated by default as identity, updated_at timestamp(6) with time zone, last_run_status varchar(16), status varchar(16) not null, type varchar(32) not null, schedule varchar(64), tenant_id varchar(64) not null, workspace_id varchar(64) not null, name varchar(128) not null, owner varchar(128), config varchar(4096), primary key (id));
create index idx_dag_run_dag_id on dag_run (dag_id);
create index idx_dag_run_status on dag_run (status);
create index idx_dag_run_biz_time on dag_run (biz_time);
create index idx_dag_run_tenant_id on dag_run (tenant_id);
create index idx_dag_run_tenant_dag on dag_run (tenant_id, dag_id);
