-- Flyway 基线迁移：metadata-collector
-- 来源：逐个 JPA 实体逐字段推导（@Table/@Id/@GeneratedValue/@Column/@Lob 等），类型按 PostgreSQL 方言映射：
--         Long+IDENTITY → bigint generated by default as identity；Long → bigint；Integer → integer；
--         String 默认 varchar(255)；String @Column(length=N) → varchar(N)；
--         @Lob String → oid；LocalDateTime → timestamp(6)（无时区）。
--       注：实体上的 @NotBlank 属 Bean Validation，Hibernate 6+ 已不再据此生成 NOT NULL。
-- 实体→表映射依据（文件:行号）：
--   metadata_sources   ← MetadataSource.java:29,43-93
--   collection_history ← CollectionHistory.java:25,29-59
-- 说明：本环境无法运行 scripts/gen-db-baseline.sh（Maven 离线缺 tools.jackson:jackson-bom:3.1.7，
--       且本地仓库不可写），故本文件为按实体逐字段手写；请在可联网环境重跑生成器复核。
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table metadata_sources (id bigint generated by default as identity, name varchar(255), tenant_id varchar(64), type varchar(255), url varchar(255), username varchar(255), password varchar(255), connection_props oid, cron varchar(255), status varchar(255), created_at timestamp(6), updated_at timestamp(6), primary key (id));
create table collection_history (id bigint generated by default as identity, source_id bigint, trigger_type varchar(255), status varchar(255), started_at timestamp(6), finished_at timestamp(6), duration_ms bigint, table_count integer, column_count integer, error_message oid, primary key (id));
