-- Flyway 基线迁移：dashboard
-- 由 Hibernate 按 PostgreSQL 方言生成（jakarta.persistence.schema-generation.scripts.action=create），
-- 字段与 JPA 实体一一对应，非手写。重新生成：bash scripts/gen-db-baseline.sh platform/finops/dashboard
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table bi_dashboard (created_at timestamp(6) with time zone not null, id bigint generated by default as identity, updated_at timestamp(6) with time zone, tenant_id varchar(64) not null, name varchar(128) not null, description varchar(512), panels_json varchar(16384), primary key (id));
