apiVersion: v2
name: superset
description: Apache Superset 数据可视化 BI - 数据引擎大数据平台
type: application
version: 0.1.0
appVersion: "4.1.1"
home: https://github.com/DataEngineBDP
maintainers:
  - name: DataEngineBDP Team
    email: platform@shuqing.example.com
keywords:
  - big-data
  - superset
  - shuqing-platform
