apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertRules.existingConfigMap | default (printf "%s-alert-rules" (include "prometheus.fullname" .)) }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/rules/*.yaml" }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
