-- Flyway 基线迁移：rule-engine
-- 来源：逐个 JPA 实体逐字段推导（@Table/@Id/@GeneratedValue 等），类型按 PostgreSQL 方言映射：
--         Long+IDENTITY → bigint generated by default as identity；String 默认 varchar(255)；
--         LocalDateTime → timestamp(6)（无时区）；Boolean → boolean。
-- 实体→表映射依据（文件:行号）：
--   rules ← Rule.java:24,28-63
-- 说明：本环境无法运行 scripts/gen-db-baseline.sh（Maven 离线缺 tools.jackson:jackson-bom:3.1.7，
--       且本地仓库不可写），故本文件为按实体逐字段手写；请在可联网环境重跑生成器复核。
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table rules (id bigint generated by default as identity, name varchar(255), description varchar(255), type varchar(255), expression varchar(255), severity varchar(255), enabled boolean, tenant_id varchar(255), created_at timestamp(6), updated_at timestamp(6), primary key (id));
