# ============================================================================
# kafka · dev 环境 values
# 策略：broker=1,controller=1 · 资源最小 · kraft · retention 24h · 无PVC
# ============================================================================

image:
  repository: "apache/kafka"
  tag: "3.7.0"
  pullPolicy: IfNotPresent

replicas: 1

resources:
  requests: { cpu: "500m", memory: "1Gi" }
  limits:   { cpu: "1",    memory: "2Gi" }

config:
  broker:
    replicas: 1
    minInSyncReplicas: 1
    defaultReplicationFactor: 1
    compressionType: lz4
    logRetentionHours: 24
  metadata:
    mode: kraft
    kraft:
      controllers: 1
  log:
    level: DEBUG

autoscaling:
  enabled: false
