{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "model-finetuning.fullname" . }}
  labels:
    {{- include "model-finetuning.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "model-finetuning.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port | int }}
  egress:
    - {}
{{- end }}
