-- Flyway 基线迁移：cost-model
-- 来源：逐个 JPA 实体逐字段推导（@Table/@Id/@GeneratedValue/@Column 等），类型按 PostgreSQL 方言映射：
--         Long+IDENTITY → bigint generated by default as identity；long → bigint not null；
--         String @Column(length=N) → varchar(N)；Long → bigint；boolean → boolean not null；
--         Instant → timestamp(6) with time zone。
-- 实体→表映射依据（文件:行号）：
--   query_metering ← QueryMeteringRecord.java:27,33-72
--   index idx_metering_tenant_ts (tenant_id, created_at) ← :28 columnList "tenantId,createdAt"
--   index idx_metering_engine (engine)                   ← :29 columnList "engine"
-- 说明：本环境无法运行 scripts/gen-db-baseline.sh（Maven 离线缺 tools.jackson:jackson-bom:3.1.7，
--       且本地仓库不可写），故本文件为按实体逐字段手写；请在可联网环境重跑生成器复核。
-- 请勿手工编辑本文件；后续结构变更请新增 V2__xxx.sql（Flyway 校验已应用脚本的 checksum）。

create table query_metering (id bigint generated by default as identity, tenant_id varchar(64) not null, namespace varchar(64), engine varchar(16) not null, sql_hash varchar(64), bytes_scanned bigint not null, estimated boolean not null, duration_ms bigint, client_request_id varchar(64) not null, created_at timestamp(6) with time zone not null, primary key (id));
create index idx_metering_tenant_ts on query_metering (tenant_id, created_at);
create index idx_metering_engine on query_metering (engine);
