apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
    - name: raft
      port: {{ .Values.service.ports.raft }}
      targetPort: raft
      protocol: TCP
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
    - name: raft
      port: {{ .Values.service.ports.raft }}
      targetPort: raft
      protocol: TCP
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
